### ISSUE TITLE
Lecture d'oeuvres - date validation

### ISSUE THREAD

**Issue by lucaguindani** [unil-lettres/dilps#40]
When the dates are entered, they are sometimes not recognized (validated). The issue
 does not appear systematically; it seems to appear randomly.

![60569360-7fa59700-9d6f-11e9-88e9-29914052bbd0](https://user-images.githubusercontent.com/1675064/60575905-a4543b80-9d7c-11e9-9efc-9dad0ec9045d.jpg)

**Comment by sambaptista** [comment]
Ca semble être lié à une absence de règle pour interpréter le "Dès". Mais je vais vérifier avec mon collègue.

Si je prends la requête ci-dessous qui affiche toutes les dates générées pour les fiches dont la règle est "Dès xxx" :

~~~sql
select c.id, c.dating, d.id
from card c
left join dating d on d.card_id = c.id
where c.dating like '%Dès%'
and d.id is null
group by c.id;
~~~

On se rend compte qu'il n'y a jamais de plage d'années trouvées.  Dans la classe DatingRule il n'y pas non plus de mention à une règles de type "Dès les années 50". 

De plus, ici on affiche la valeur de card.dating car c'est une valeur lisible par les "humains", mais le système base sa recherche sur la base des années générées à partir de cette règle et ne trouve rien. Ce qui explique sûrement qu'il ne trouve pas de correspondance.

**Plus globalement :**

~~~sql 
select c.id, c.dating, group_concat(d.id)
from card c
left join dating d on d.card_id = c.id
where c.dating <> ''
and d.id is null
group by c.id;
~~~

On voir qu'il y a 20'000 fiches qui sont une valeur dans "card.dating" mais qui n'ont aucune correspondance dans dating.to/from. Ce qui montre que le système est aussi incomplet que potentiellement fragile.

C'est d'ailleurs une des faiblesses du système de dilps et que nous conseillons d'abandonner en faveur du système de Tiresias (catégorisation des "ères"). C'est un des points de notre dernier mail adressé à Nadya hier (mercredi 25).

**Comment by PowerKiKi** [comment]
Je confirme ce que dit Samuel `DatingRule` est incomplet et fragile. Adopter le système de Tiresias, qui est à la fois flexible, précis et simple, me semble être la bonne solution à terme.

**Comment by lucaguindani** [comment]
Merci pour ces précisions.

En attendant une décision sur un changement de fonctionnement des dates sur Dilps, il serait bien de corriger ce bug en particulier qui pose un problème aux étudiants pour leurs révisions.

**Comment by PowerKiKi** [comment]
Les règles de datation ci-dessous sont issues du dump direct et complet du vieux Dilps, avant migration vers le nouveau Dilps. Dans ces règles il n'existe jamais de référence à "Dès".

Dans le nouveau Dilps nous n'avons que reproduit ces règles existantes.

Ce ticket n'est donc techniquement pas un bug, mais une nouvelle feature. Et cela met bien en évidence la fragilité de ce système (comparé à celui de Tiresias).


| seq | type    | regexp                                                                                                                                                                                          | from                                                                                                                         | to                                                                                                                             | descr                                                                                                                                          |
|-----|---------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------|
| 0   | match   | /^[[:space:]]*([[:digit:]]{2})[[:space:]]*$/                                                                                                                                                    | return _GregorianToJD( 1, 1, intval("19"".$match[1]) );"                                                                     | return _GregorianToJD( 12, 31, intval("19"".$match[1]) );"                                                                     | 64 == 1.1.1964 - 31.12.1964                                                                                                                    |
| 0   | match   | /^[[:space:]]*(um|nach|vor)?[[:space:]]*([[:digit:]]{3,4})[[:space:]]*-[[:space:]]*([[:digit:]]{1,4})[[:space:]]*$/                                                                             | return _GregorianToJD( 1,1,intval($match[2]) );                                                                              | return _GregorianToJD( 12,31,intval(substr($match[2],0,max( 0, strlen($match[2])-strlen($match[3]))).$match[3]) );             | 1875-1877 == 1.1.1875 - 31.12.18771875-77 == 1.1.1875 - 31.12.18771875/77 == 1.1.1875 - 31.12.1877                                             |
| 3   | match   | /^[[:space:]]*([[:digit:]]{1,2})[\.]?[[:space:]]*Jh[[:space:]]*$/                                                                                                                               | return _GregorianToJD( 1,1,intval((intval($match[1])-1)."00"") );"                                                           | return _GregorianToJD( 12,31,intval((intval($match[1])-1)."99"") );"                                                           | 6. Jhdt.  == 1.1.500 - 31.12.5996. Jhdt. n Chr. == 1.1.500 - 31.12.5996 Jhd  n. Chr == 1.1.500 - 31.12.5996 Jh. n. Chr. == 1.1.500 - 31.12.599 |
| 3   | match   | /^[[:space:]]*um[[:space:]]*([[:digit:]]{3,4})[[:space:]]*$/                                                                                                                                    | return _GregorianToJD( 1,1,intval($match[1])) - intervalFromYear( $match[1] );                                               | return _GregorianToJD( 12,31,intval($match[1])) + intervalFromYear( $match[1] );                                               | um 1874 == 1873 - 1875                                                                                                                         |
| 3   | match   | /^[[:space:]]*Anf(ang)?\.?([[:space:]]*des)?[[:space:]]*([[:digit:]]{1,2})[\.]?[[:space:]]*Jh[[:space:]]*$/                                                                                     | return _GregorianToJD( 1,1,intval((intval($match[3])-1)."00"") );"                                                           | return _GregorianToJD( 12,31,intval((intval($match[3])-1)."25"") );"                                                           | Anfang 6. Jhdt. == 1.1.500 - 31.12.525                                                                                                         |
| 7   | match   | /^[[:space:]]*(um|nach|vor)?[[:space:]]*([[:digit:]]{1,2})\.?[[:space:]]*-[[:space:]]*([[:digit:]]{1,2})\.?[[:space:]]*Jh[[:space:]]*$/                                                         | return _GregorianToJD( 1,1,intval((intval($match[3])-1)."00"") );"                                                           | return _GregorianToJD( 12,31,intval((intval($match[2]))."99"") );"                                                             | 1. - 2. Jh. n. Chr. == 1.1.0 - 31.12.299                                                                                                       |
| 0   | match   | /^[[:space:]]*([[:digit:]]{3,4})[[:space:]]*vor[[:space:]]Chr\.?[[:space:]]*$/                                                                                                                  | return _GregorianToJD( 1,1,-intval($match[1]) );                                                                             | return _GregorianToJD( 12,31,-intval($match[1]) );                                                                             | 1875 v. Chr. == 1.1.-1875 - 31.12.-1875                                                                                                        |
| 0   | match   | /^xxx[[:space:]]*(um|nach|vor)?[[:space:]]*([[:digit:]]{3,4})[[:space:]]*[-\\/]{1}[[:space:]]*([[:digit:]]{3,4})[[:space:]]*$/                                                                  | return _GregorianToJD( 1,1,intval($match[2]) );                                                                              | return _GregorianToJD( 12,31,intval($match[3]) );                                                                              | 1875-1877 == 1.1.1875 - 31.12.1877                                                                                                             |
| 3   | match   | /^[[:space:]]*([[:digit:]]{1,2})[\.]?[[:space:]]*Jh[[:space:]]*vor[[:space:]]*Chr\.?[[:space:]]*$/                                                                                              | return _GregorianToJD( 1,1,-intval((intval($match[1]))."00"") );"                                                            | return _GregorianToJD( 12,31,-intval((intval($match[1])-1)."01"") );"                                                          | 6. Jhdt. v. Chr. == 1.1.-501 - 31.12.-600                                                                                                      |
| 3   | match   | /^[[:space:]]*(um|nach|vor)?[[:space:]]*([[:digit:]]{1,2})\.?[[:space:]]*-[[:space:]]*([[:digit:]]{1,2})\.?[[:space:]]*Jh[[:space:]]*$/                                                         | return _GregorianToJD( 1,1,intval((intval($match[2])-1)."00"") );"                                                           | return _GregorianToJD( 12,31,intval((intval($match[3])-1)."99"") );"                                                           | 6. Jhdt. n. Chr. == 1.1.500 - 31.12.599                                                                                                        |
| 0   | match   | /^[[:space:]]*([[:digit:]]{3,4})[[:space:]]*$/                                                                                                                                                  | return _GregorianToJD( 1,1,intval($match[1]) );                                                                              | return _GregorianToJD( 12,31,intval($match[1]) );                                                                              | 1875 n. Chr. == 1.1.1875 - 31.12.18751875  == 1.1.1875 - 31.12.1875                                                                            |
| 0   | match   | /^[[:space:]]*(um)?[[:space:]]*([[:digit:]]+)[[:space:]]*-[[:space:]]*([[:digit:]]+)[[:space:]]*vor[[:space:]]Chr\.?[[:space:]]*$/                                                              | return _GregorianToJD( 1,1,-max(intval($match[2]),intval($match[3])) );                                                      | return _GregorianToJD( 12,31,-min(intval($match[2]),intval($match[3])) );                                                      | 1876-1872 v. Chr. == 1.1.-1876 - 31.12.-1872                                                                                                   |
| 3   | match   | /^[[:space:]]*Ende([[:space:]]*des)?[[:space:]]*([[:digit:]]{1,2})[\.]?[[:space:]]*Jh[[:space:]]*$/                                                                                             | return _GregorianToJD( 1,1,intval((intval($match[2])-1)."75"") );"                                                           | return _GregorianToJD( 12,31,intval((intval($match[2])-1)."99"") );"                                                           | Ende 6. Jhdt. == 1.1.575 - 31.12.599                                                                                                           |
| 7   | match   | /^[[:space:]]*(um|nach|vor)?[[:space:]]*([[:digit:]]{1,2})\.?[[:space:]]*-[[:space:]]*([[:digit:]]{1,2})\.?[[:space:]]*Jh[[:space:]]*vor[[:space:]]*Chr\.?[[:space:]]*(\\(.*\\))?[[:space:]]*$/ | return _GregorianToJD( 1,1,-intval((max(intval($match[2]),intval($match[3])))."00"") );"                                     | return _GregorianToJD( 12,31,-intval((min(intval($match[2]),intval($match[3]))-1)."01"") );"                                   | 2. - 1. Jh. v. Chr. == 1.1.-199 - 31.12.1                                                                                                      |
| 0   | match   | /^[[:space:]]*um[[:space:]]*([[:digit:]]+)[[:space:]]*vor[[:space:]]Chr\.?[[:space:]]*(\\(.*\\))?[[:space:]]*$/                                                                                 | return _GregorianToJD( 1,1,-intval($match[1]) ) - intervalFromYear( -intval($match[1]) );                                    | return _GregorianToJD( 12,31,-intval($match[1]) ) + intervalFromYear( -intval($match[1]) );                                    | um 1875 v. Chr. == 1.1.-1875 - 31.12.-1875                                                                                                     |
| 3   | match   | /^[[:space:]]*([[:digit:]]{1})\\.?[[:space:]]*(h\\.|haelfte|hï¿½lfte)[[:space:]]*(des[[:space:]]*)?([[:digit:]]{1,2})[\.]?[[:space:]]*Jh[[:space:]]*$/                                          | return _GregorianToJD( 1,1,intval((intval($match[4])-1)."00"")+50*(intval($match[1])-1)  );"                                 | return _GregorianToJD( 12,31,intval((intval($match[4])-1)."49"")+50*(intval($match[1])-1)  );"                                 | 1. hï¿½lfte. 6. Jhdt. == 1.1.500 - 31.12.549                                                                                                   |
| 3   | match   | /^[[:space:]]*([[:digit:]]{1})\\.?[[:space:]]*(h\\.|haelfte|hï¿½lfte)[[:space:]]*(des[[:space:]]*)?([[:digit:]]{1,2})[\.]?[[:space:]]*Jh[[:space:]]*vor[[:space:]]Chr\.?[[:space:]]*$/          | return _GregorianToJD( 1,1,-intval((intval($match[4]))."00"")-50*(intval($match[1])-1)  );"                                  | return _GregorianToJD( 12,31,-intval((intval($match[4])-1)."51"")-50*(intval($match[1])-1)  );"                                | 1. hï¿½lfte. 6. Jhdt. v. chr. == 1.1.-600 - 31.12.-551                                                                                         |
| 3   | match   | /^[[:space:]]*([[:digit:]]{1})\\.?[[:space:]]*(v\\.|viertel)[[:space:]]*(des[[:space:]]*)?([[:digit:]]{1,2})[\.]?[[:space:]]*Jh[[:space:]]*$/                                                   | return _GregorianToJD( 1,1,intval((intval($match[4])-1)."00"")+25*(intval($match[1])-1)  );"                                 | return _GregorianToJD( 12,31,intval((intval($match[4])-1)."24"")+25*(intval($match[1])-1)  );"                                 | 1. viertel 6. Jhdt. == 1.1.500 - 31.12.524                                                                                                     |
| 3   | match   | /^[[:space:]]*([[:digit:]]{1})\\.?[[:space:]]*(v\\.|viertel)[[:space:]]*(des[[:space:]]*)?([[:digit:]]{1,2})[\.]?[[:space:]]*Jh[[:space:]]*vor[[:space:]]Chr\.?[[:space:]]*$/                   | return _GregorianToJD( 1,1,-intval((intval($match[4]))."00"")-25*(intval($match[1])-1)  );"                                  | return _GregorianToJD( 12,31,-intval((intval($match[4])-1)."76"")-25*(intval($match[1])-1)  );"                                | 1. viertel 6. Jhdt. v. chr == 1.1.-600 - 31.12.-576                                                                                            |
| 3   | match   | /^[[:space:]]*([[:digit:]]{1})\\.?[[:space:]]*(dr\\.|drittel)[[:space:]]*(des[[:space:]]*)?([[:digit:]]{1,2})[\.]?[[:space:]]*Jh[[:space:]]*$/                                                  | return _GregorianToJD( 1,1,intval((intval($match[4])-1)."00"")+33*(intval($match[1])-1)  );"                                 | return _GregorianToJD( 12,31,intval((intval($match[4])-1)."32"")+33*(intval($match[1])-1)  );"                                 | 1. drittel 6. Jhdt. == 1.1.500 - 31.12.532                                                                                                     |
| 3   | match   | /^[[:space:]]*([[:digit:]]{1})\\.?[[:space:]]*(dr\\.|drittel)[[:space:]]*(des[[:space:]]*)?([[:digit:]]{1,2})[\.]?[[:space:]]*Jh[[:space:]]*vor[[:space:]]Chr\.?[[:space:]]*$/                  | return _GregorianToJD( 1,1,-intval((intval($match[4]))."00"")-33*(intval($match[1])-1)  );"                                  | return _GregorianToJD( 12,31,-intval((intval($match[4])-1)."68"")-33*(intval($match[1])-1)  );"                                | 1. drittel. 6. Jhdt. v. chr == 1.1.-600 - 31.12.-568                                                                                           |
| 3   | match   | /^[[:space:]]*vor[[:space:]]*([[:digit:]]{3,4})[[:space:]]*$/                                                                                                                                   | return _GregorianToJD( 1,1,intval($match[1])) - intervalFromYear( $match[1] );                                               | return _GregorianToJD( 12,31,intval($match[1]));                                                                               | vor 1874 == 1869 - 1874                                                                                                                        |
| 0   | match   | /^[[:space:]]*nach[[:space:]]*([[:digit:]]+)[[:space:]]*vor[[:space:]]Chr\.?[[:space:]]*(\\(.*\\))?[[:space:]]*$/                                                                               | return _GregorianToJD( 1,1,-intval($match[1]) ) - intervalFromYear( -intval($match[1]) );                                    | return _GregorianToJD( 12,31,-intval($match[1]) );                                                                             | vor 1875 v. Chr. == 1.1.-1795 - 31.12.-1875                                                                                                    |
| 3   | match   | /^[[:space:]]*mitte[[:space:]]*(des[[:space:]]*)?([[:digit:]]{1,2})[\.]?[[:space:]]*Jh[[:space:]]*$/                                                                                            | return _GregorianToJD( 1,1,intval((intval($match[2])-1)."33"") );"                                                           | return _GregorianToJD( 12,31,intval((intval($match[2])-1)."66"") );"                                                           | mitte 6. Jhdt. == 1.1.533 - 31.12.566                                                                                                          |
| 3   | match   | /^[[:space:]]*mitte[[:space:]]*(des[[:space:]]*)?([[:digit:]]{1,2})[\.]?[[:space:]]*Jh[[:space:]]*vor[[:space:]]Chr\.?[[:space:]]*$/                                                            | return _GregorianToJD( 1,1,-intval((intval($match[2]))."00"")-66);"                                                          | return _GregorianToJD( 12,31,-intval((intval($match[2]))."00"")-33);"                                                          | mitte 6. Jhdt. v. chr == 1.1.-567 - 31.12.-533                                                                                                 |
| 0   | replace |                                                                                                                                                                                                 | /zwischen[[:space:]]*([[:digit:]\\.]+)[[:space:]]*(und|-)/                                                                   | $1 -                                                                                                                           |                                                                                                                                                |
| 0   | replace |                                                                                                                                                                                                 | /[[:space:]]*\\(.*\\)[[:space:]]*/                                                                                           |                                                                                                                                |                                                                                                                                                |
| 0   | replace |                                                                                                                                                                                                 | /(around|ca\\.?|~|begonnen|ab|vor|nach)/                                                                                     |                                                                                                                                |                                                                                                                                                |
| 0   | replace |                                                                                                                                                                                                 | /(jahrhunderts?|jhd?t?s?\\.?)/                                                                                               | jh                                                                                                                             |                                                                                                                                                |
| 0   | replace |                                                                                                                                                                                                 | /(v\\.|vor)[[:space:]]*(christus|chr?\\.?)/                                                                                  | vor chr                                                                                                                        |                                                                                                                                                |
| 0   | replace |                                                                                                                                                                                                 | /(n\\.|nach)[[:space:]]*chr\\.?/                                                                                             |                                                                                                                                |                                                                                                                                                |
| 0   | replace |                                                                                                                                                                                                 | /(\\/|bis)/                                                                                                                  | -                                                                                                                              |                                                                                                                                                |
| 0   | replace |                                                                                                                                                                                                 | /[[:space:]]+/                                                                                                               |                                                                                                                                |                                                                                                                                                |
| 0   | replace |                                                                                                                                                                                                 | /erstes/                                                                                                                     | 1                                                                                                                              |                                                                                                                                                |
| 0   | replace |                                                                                                                                                                                                 | /fr(ï¿½|ue|u)hes/                                                                                                            | anfang                                                                                                                         |                                                                                                                                                |
| 0   | replace |                                                                                                                                                                                                 | /sp(ï¿½|ae|a)tes/                                                                                                            | ende                                                                                                                           |                                                                                                                                                |
| 3   | match   | /^[[:space:]]*um[[:space:]]*([[:digit:]]{1,2})[\.]?[[:space:]]*Jh[[:space:]]*$/                                                                                                                 | return _GregorianToJD( 1,1,intval((intval($match[1])-1)."00"") ) - intervalFromYear( intval((intval($match[1])-1).""00""));" | return _GregorianToJD( 12,31,intval((intval($match[1])-1)."99"") ) + intervalFromYear( intval((intval($match[1])-1).""99""));" | um 6. Jhdt.  == 1.1.480 - 31.12.620                                                                                                            |
| 3   | match   | /^[[:space:]]*nach[[:space:]]*([[:digit:]]{3,4})[[:space:]]*$/                                                                                                                                  | return _GregorianToJD( 1,1,intval($match[1]));                                                                               | return _GregorianToJD( 12,31,intval($match[1])) + intervalFromYear( $match[1] );                                               | nach 1874 == 1874 - 1875                                                                                                                       |
| 0   | match   | /^[[:space:]]*nach[[:space:]]*([[:digit:]]+)[[:space:]]*vor[[:space:]]Chr\.?[[:space:]]*(\\(.*\\))?[[:space:]]*$/                                                                               | return _GregorianToJD( 1,1,-intval($match[1]) );                                                                             | return _GregorianToJD( 12,31,-intval($match[1]) ) + intervalFromYear( -intval($match[1]) );                                    | nach 1875 v. Chr. == 1.1.-1875 - 31.12.-1860                                                                                                   |
| 0   | replace |                                                                                                                                                                                                 | /(gegen|vollendet)/                                                                                                          | vor                                                                                                                            |                                                                                                                                                |
| 0   | replace |                                                                                                                                                                                                 | /letztes[[:space:]]*viertel/                                                                                                 | 4. viertel                                                                                                                     |                                                                                                                                                |
| 0   | replace |                                                                                                                                                                                                 | /letztes[[:space:]]*drittel/                                                                                                 | 3. drittel                                                                                                                     |                                                                                                                                                |
| 0   | match   | /^[[:space:]]*([[:digit:]]{2}).([[:digit:]]{2}).([[:digit:]]{4})[[:space:]]*$/                                                                                                                  | return _GregorianToJD( intval( $match[1]), intval( $match[2]), intval( $match[3]) );                                         | return _GregorianToJD( intval( $match[1]), intval( $match[2]), intval( $match[3]) );                                           | 23.10.2003 == 23.10.2003 - 23.10.2003                                                                                                          |
| 0   | match   | /^[[:space:]]*spï¿½t[[:space:]]*antike[[:space:]]*$/                                                                                                                                            | return _GregorianToJD( 1, 1, 275 );                                                                                          | return _GregorianToJD( 12, 31, 525 );                                                                                          | spï¿½tantike == 1.1.275 - 31.12.525                                                                                                            |
| 0   | match   | /^[[:space:]]*shang[[:space:]-]*dynastie[[:space:]]*$/                                                                                                                                          | return _GregorianToJD( 1, 1, -1625 );                                                                                        | return _GregorianToJD( 12, 31, -975 );                                                                                         | Shang-Dynastie == 16 - 11 Jh. v. Chr                                                                                                           |
| 0   | match   | /^[[:space:]]*vor[[:space:]]*([[:digit:]]+)[[:space:]]*vor[[:space:]]Chr\.?[[:space:]]*(\\(.*\\))?[[:space:]]*$/                                                                                | return _GregorianToJD( 1,1,-intval($match[1]) ) - intervalFromYear( -intval($match[1]) );                                    | return _GregorianToJD( 12,31,-intval($match[1]) );                                                                             | um 1875 v. Chr. == 1.1.-1875 - 31.12.-1875                                                                                                     |
| 0   | match   | /^[[:space:]]*antike[[:space:]]*$/                                                                                                                                                              | return _GregorianToJD( 1, 1, -825 );                                                                                         | return _GregorianToJD( 12, 31, 525 );                                                                                          | antike == 1.1.-825 - 31.12.525                                                                                                                 |
| 0   | replace |                                                                                                                                                                                                 | /(u\\.|und|bzw\\.?|oder)/                                                                                                    | ;                                                                                                                              |                                                                                                                                                |

**Comment by PowerKiKi** [comment]
Pour info, nous sommes en attente des chose suivante de la part de l'UNIL avant de faire qqch ici:

 * Validation d'une recherche partielle sur le champ datation dans une lecture d'oeuvre 
   * `Avant 1603` retourne true si card.datation est égal à `dès 1603`
   * comportement à valider : recherche partielle pour les autres champs texte

**Comment by lucaguindani** [comment]
>   * `Avant 1603` retourne true si card.datation est égal à `dès 1603`

Ca semble être plutôt `Après 1603` qui devrait retourner true si card.datation est égal à `dès 1603` ?

>   * comportement à valider : recherche partielle pour les autres champs texte

C'est bien le comportement actuel et aussi le comportement attendu.

**Comment by PowerKiKi** [comment]
> Ca semble être plutôt Après 1603 qui devrait retourner true si card.datation est égal à dès 1603 ?

C'est précisement le problème qui sera introduit si on fait ce que vous voulez. Et cela donc doit être confirmé si c'est acceptable ou non.

**Comment by lucaguindani** [comment]
Oui ok je comprends, ça semble étrange, mais c'est effectivement inévitable avec le fonctionnement actuel. Donc on peut y aller avec une recherche partielle également sur le champ datation, c'est un effet secondaire qui est déjà présent sur les autres champs de toute façon.

**Comment by PowerKiKi** [comment]
Corrigé dans dans 5b7b502a0256026ea6528c00ccfcb185226aa3c9
