### ISSUE TITLE
Search - "dating" field is not taken into account

### ISSUE THREAD

**Issue by lucaguindani** [unil-lettres/dilps#53]
In the **general search**, the "dating" field is not taken into account. This means that a work dated 1352 does not come out if you search for the string "1352" in the general search. It only comes out when you enter 1352 to 1352 in the advanced search dating, but it comes out with all the records that have the year 1352 in their chronological range. The work then becomes almost impossible to find.

**Comment by PowerKiKi** [comment]
Fixed in 0a17b211d157c760dd6bbbc007dd862e3ac4c523
