### ISSUE TITLE
Limited fields in cards

### ISSUE THREAD

**Issue by lucaguindani** [unil-lettres/dilps#54]
In dilps some fields of the cards are limited to about 256 characters. When they are exceeded, there is no warning message. At first sight, the card is recorded normally but everything beyond that is actually cut off.

This is problematic for Dilps, but it will especially pose a huge concern to Tiresias who publishes very long texts in his description field. It is essential to be aware of this before importing Tiresias data into dilps, as this could result in the loss of a significant amount of information.

**Comment by PowerKiKi** [comment]
Fixed in 2fb8fd7e2df63ad89c67ddf890efdf786af3bbfa and bcaf05d98592f41ae7cbea85fe405987be7c1aa3
